### ISSUE TITLE
Cannot add inline styles to the container div

### ISSUE THREAD

**Issue by dong-516** [httptoolkit/react-reverse-portal#11]
Hi,I really appreciate your work, it soved my problem, but it does not full up the parent of the component, what I did was just add a line 61, the code looks like this:
if (elementType === ELEMENT_TYPE_HTML) {
        element= document.createElement('div');
        element.style.cssText = 'width:100%;height:100%;';
    }

I do not know whether I have changed your code in the right way or in a wrong way, looking forward to your reply,

with many thanks!

**Comment by pimterry** [comment]
Ok, I think I understand.

I don't think that the container div should have those styles by default, but I can see why it might be useful to include them in some cases.

Is there a reason why you can't do that in CSS elsewhere? Like:

```
.yourPortalContainer > div {
  width: 100%;
  height: 100%;
} 
```

It's probably possible to add a `style` option to nodes to allow adding inline styles, but I suspect the above is usually a better idea. Another option might be a `className` property, which would probably integrate more easily with styled components etc.

**Comment by dong-516** [comment]
thanks for your replay,
 you get the point.
since I am a novice in html css and javascript area, your suggestion may work in other case, but it do not work in my case, what I have to do is to down load your source code and change it as above, and add into my project,but add a reference to your github website, very pity! what I did is ok？
thanks for your help!

**Comment by pimterry** [comment]
Hmm, ok. I think it probably would work in your case, but it depends how your existing CSS works. How do you set styles in the rest of your application?

This package is open source, so of course you're very welcome to download the source and edit if you like, but you might discover big problems later: e.g. when you want to use different styles in different places then you'll need to do something much more complicated.

You should be able to do something equivalent to the above CSS, in the same place you do the rest of your styling, and if you do that then it's likely to be a bit more flexible and reliable in future. Whatever works for you though.

**Comment by pimterry** [comment]
Ok, I'm going to close this for now.

I think for most cases using standalone CSS elsewhere is simpler and clearer, rather than trying to add inline styles to the node itself (and I would definitely recommend _against_ programmatically setting styles from inside the lib, as above).

I am open to discussing other potential ways to solve this though, if there's a clear use case where it's important for react-reverse-portal to allow direct configuration of inline styles etc or classnames on the container itself.

**Comment by dong-516** [comment]
thanks for your suggestion, 
actually, this code snippet works:
.yourPortalContainer > div {
  width: 100%;
  height: 100%;
} 
what works is the symbol '>',  which means targeting to the direct children of the container.
thanks a lot!
