### ISSUE TITLE
Any way to prevent unmounting of the portal contents when changing portals that aren't located within the same component?

### ISSUE THREAD

**Issue by Slapbox** [httptoolkit/react-reverse-portal#17]
I noticed all of the examples are limited to toggling between portals within the same component. Unfortunately if you swap portals that are within child components, you get unmounts every time you swap. Is there any way around this?

[Example](https://codesandbox.io/s/sleepy-montalcini-icl9r?file=/src/App.js)

Thanks for sharing this awesome library!

**Comment by Slapbox** [comment]
Whoops I think I set things up backwards...

**Comment by pimterry** [comment]
Haha, glad you got this sorted @Slapbox! Sorry if things weren't clear - if there was anything specifically in the README that lead you astray, feel free to open a PR to clarify it :smiley:
