### ISSUE TITLE
Does not work with SVGs

### ISSUE THREAD

**Issue by williammetcalf** [httptoolkit/react-reverse-portal#2]
It looks like the `OutPortal` wraps the content in a `<div>`, which results in the content not actually being rendered if it is used within a `<svg>` since `div`s cant exist in `svg`s.

It would be nice if you could specify an optional `component` prop or something to be used a wrapper for this render. If it was wrapped in a `<g>` for example, I imagine it would work fine.

Example that doesn't actually work:

```tsx
import React, { FC, useMemo } from "react";
import { createPortalNode, InPortal, OutPortal } from "react-reverse-portal";

const Test: FC = () => {
  const portal = useMemo(() => createPortalNode(), []);

  return (
    <div>
      <svg>
        <rect x={0} y={0} width={300} height={50} fill="gray"></rect>
        <rect x={0} y={50} width={300} height={50} fill="lightblue"></rect>
        <svg x={30} y={10}>
          <InPortal node={portal}>
            <text alignmentBaseline="text-before-edge" fill="red">
              test
            </text>
          </InPortal>
        </svg>
        <svg x={30} y={70}>
          <OutPortal node={portal} />
        </svg>
      </svg>
    </div>
  );
};

export default Test;

```

**Comment by pimterry** [comment]
Ah, yes, that makes sense.

To be honest I don't know much about SVGs. I'll try and find some time to look at this properly soon, but in the meantime if you're better informed and you have a minute I'd very happily accept a PR to support this!

**Comment by RusinovAnton** [comment]
Since OutPortal relies on the `ref` prop, `React.Fragment` can't be used.
There should be a possibility to pass a prop `OutPortal` with the element which to render instead of the default `div`

**Comment by pimterry** [comment]
@williammetcalf This has now been fixed! If you'd like to use SVGs with react-reverse-portal, you just need to upgrade to v2.0.0+, and use `createSvgPortalNode`. Thanks for reporting this, glad we could get it sorted.
