### ISSUE TITLE
Migrate from Travis to Github Actions?

### ISSUE THREAD

**Issue by spautz** [httptoolkit/react-reverse-portal#26]
It looks like this repo is still using travis-ci.org for CI, which is deprecated and slated for shutdown at some point.

Migrating to travis-ci.com is an option, but personally I've found Github Actions to be a nicer experience. If it sounds worthwhile and desirable, I'd be happy to submit a PR to migrate from Travis to Github Actions -- likely a diff similar to https://github.com/spautz/limited-cache/pull/38/files

Or if some other CI system seems better, it may be worth looking at before Travis kills off their .org service

**Comment by pimterry** [comment]
Yes, absolutely! Most of the other repos in this org have been migrated already, it's only that I haven't got to it here yet. If you have time, a PR for that would be very welcome :+1:
