### ISSUE TITLE
Queries around library usage

### ISSUE THREAD

**Issue by Anand2489** [httptoolkit/react-reverse-portal#31]
Can we use this library in production level code or there are some limitations which should be highlighted ?

I have following queries around it though :-

1. New parent would be able to completely control InPortal component via props & refs
2. InPortal component would get new props in current render cycle of the parent without any delay
3. Any case/scenario where teleporting components via react-reverse-portal won't work :)
4. Event propagation happens w.r.t to the new parent in OutPortal or the detached node where InPortal component is mounted

@pimterry ^^

**Comment by pimterry** [comment]
Yes, you can use this in production. I'm not aware of any general issues. To know if it will work in your environment I'd suggest trying it out in a small prototype, I can't really advise in much more detail without fully understanding your setup.

With regards to your questions, yes, the new parent can control props and those should apply immediately.

Event propagation goes through the InPortal, not the OutPortal (see #13). That's how react's portals work everywhere - I'm open to exploring changes there if you have suggestions though.
