### ISSUE TITLE
Add ES5 distribution?

### ISSUE THREAD

**Issue by spong** [httptoolkit/react-reverse-portal#4]
Hey @pimterry, came across this lib in the comments of https://github.com/facebook/react/issues/13044, and it has been just the thing we needed to get [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) draggables working from within other react component trees. So thanks for taking the time to put this together.  🙂 

Anyway, as unfortunate as it is, our builds need to support IE11 for just a little while longer and so we need an ES5 distribution to do that. 

I'm not sure if this is something you're open to including as it adds additional bloat and very few people need it, but I figured I'd ask. I've got this working over on my fork (https://github.com/spong/react-reverse-portal/commit/bddc9393ef2b7377cb8f1b06967670b1b52208ea) and am happy to open a PR, but just wanted to create an issue to get your feedback first.

If this isn't something you're interested in supporting, no worries at all. We can add the appropriate attribution and build from source on our end in this interim period while we still have to support IE11.

Thanks again!

**Comment by pimterry** [comment]
Awesome! I'm definitely open to considering that at least, feel free to send a PR.

Is it just that language features need to be compiled away, or is there something more fundamental that's not properly supported, like some of the DOM API or something?

**Comment by spong** [comment]
Great! And yeah, it's just language features, no issue with any DOM API's. I went the babel route with the PR for better flexibility if need be. Give it a whirl and let me know what you think. I separated out the ES5 transpilation to it's own script (`build-web`) and call that from `build`. 

Here's the PR: https://github.com/httptoolkit/react-reverse-portal/pull/5

Thanks! :)

**Comment by pimterry** [comment]
Fixed in v1.0.4
